const config = require('@rubensworks/eslint-config');

module.exports = config([
  {
    files: [ '**/*.ts' ],
    languageOptions: {
      parserOptions: {
        tsconfigRootDir: __dirname,
        project: [ './tsconfig.eslint.json' ],
      },
    },
  },
  {
    rules: {
      'antfu/consistent-list-newline': 'off',
      'antfu/top-level-function': 'off',
      'capitalized-comments': 'off',
      'function-paren-newline': 'off',
      'import/first': 'off',
      'import/newline-after-import': 'off',
      'import/no-duplicates': 'off',
      'import/no-extraneous-dependencies': 'off',
      'import/no-nodejs-modules': 'off',
      'import/order': 'off',
      'jest/no-test-return-statement': 'off',
      'jest/prefer-spy-on': 'off',
      'jest/prefer-to-be': 'off',
      'jest/require-to-throw-message': 'off',
      'jsonc/sort-keys': 'off',
      'max-len': 'off',
      'no-console': 'off',
      'no-else-return': 'off',
      'no-restricted-globals': 'off',
      'prefer-template': 'off',
      'style/arrow-parens': 'off',
      'style/indent': 'off',
      'style/member-delimiter-style': 'off',
      'style/object-curly-spacing': 'off',
      'style/operator-linebreak': 'off',
      'style/padded-blocks': 'off',
      'style/quotes': 'off',
      'style/space-before-function-paren': 'off',
      'ts/consistent-indexed-object-style': 'off',
      'ts/consistent-type-assertions': 'off',
      'ts/consistent-type-imports': 'off',
      'ts/explicit-member-accessibility': 'off',
      'ts/naming-convention': 'off',
      'ts/no-require-imports': 'off',
      'ts/no-unsafe-argument': 'off',
      'ts/no-unsafe-assignment': 'off',
      'ts/no-var-requires': 'off',
      'ts/prefer-nullish-coalescing': 'off',
      'ts/space-before-function-paren': 'off',
      'unicorn/empty-brace-spaces': 'off',
      'unicorn/filename-case': 'off',
      'unicorn/no-negated-condition': 'off',
      'unicorn/prefer-node-protocol': 'off',
      'unused-imports/no-unused-vars': 'off',
    },
  },
]);
